version: '3'
services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - 80:80/tcp
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --providers.docker.network=dns_traefik
      - --log.level=DEBUG
      - --api.dashboard=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.internal.prstat.org`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api-default.rule=PathPrefix(`/`)
      - traefik.http.routers.api-default.service=api@internal
      - traefik.http.routers.api-default.priority=1
    networks: 
      - default
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  dns-server:
    image: pihole/pihole:latest
    ports:
      - 53:53/udp
      - 53:53/tcp
      #- 67:67/udp # dhcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.dns.rule=Host(`dns.internal.prstat.org`)
      - traefik.http.routers.dns.service=dns
    environment:
      DNS_SERVER_DOMAIN: internal.prstat.org
      TZ: 'Australia/Canberra'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - config:/etc/pihole
    restart: unless-stopped
    networks:
      - traefik
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    cap_add:
      - NET_ADMIN
volumes:
  config:
networks:
  traefik:
